package fun.jwei.hungerserver.model;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.info
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sales_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer salesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.like_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.line_price
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Float linePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.parent_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type_all
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer typeAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String imgSrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.info
     *
     * @return the value of goods.info
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.info
     *
     * @param info the value for goods.info
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sales_count
     *
     * @return the value of goods.sales_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getSalesCount() {
        return salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sales_count
     *
     * @param salesCount the value for goods.sales_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setSalesCount(Integer salesCount) {
        this.salesCount = salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.like_count
     *
     * @return the value of goods.like_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.like_count
     *
     * @param likeCount the value for goods.like_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.line_price
     *
     * @return the value of goods.line_price
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Float getLinePrice() {
        return linePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.line_price
     *
     * @param linePrice the value for goods.line_price
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setLinePrice(Float linePrice) {
        this.linePrice = linePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.parent_id
     *
     * @return the value of goods.parent_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.parent_id
     *
     * @param parentId the value for goods.parent_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type_all
     *
     * @return the value of goods.type_all
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getTypeAll() {
        return typeAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type_all
     *
     * @param typeAll the value for goods.type_all
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setTypeAll(Integer typeAll) {
        this.typeAll = typeAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img_src
     *
     * @return the value of goods.img_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img_src
     *
     * @param imgSrc the value for goods.img_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc == null ? null : imgSrc.trim();
    }
}