package fun.jwei.hungerserver.model;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.title
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.img_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String imgSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.link
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.seq
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.title
     *
     * @return the value of menu.title
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.title
     *
     * @param title the value for menu.title
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.img_src
     *
     * @return the value of menu.img_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.img_src
     *
     * @param imgSrc the value for menu.img_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc == null ? null : imgSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.link
     *
     * @return the value of menu.link
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.link
     *
     * @param link the value for menu.link
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.seq
     *
     * @return the value of menu.seq
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.seq
     *
     * @param seq the value for menu.seq
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
}