package fun.jwei.hungerserver.model;

public class OrderGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.num
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.id
     *
     * @return the value of order_goods.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.id
     *
     * @param id the value for order_goods.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_id
     *
     * @return the value of order_goods.order_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_id
     *
     * @param orderId the value for order_goods.order_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_id
     *
     * @return the value of order_goods.goods_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_id
     *
     * @param goodsId the value for order_goods.goods_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.num
     *
     * @return the value of order_goods.num
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.num
     *
     * @param num the value for order_goods.num
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}