package fun.jwei.hungerserver.model;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.star
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Float star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.sales_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer salesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.min_cost
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Float minCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.deliver_cost
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Float deliverCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.tags
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.profile_pic
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String profilePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.latitude
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.longitude
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String longitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.star
     *
     * @return the value of shop.star
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Float getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.star
     *
     * @param star the value for shop.star
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setStar(Float star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.sales_count
     *
     * @return the value of shop.sales_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getSalesCount() {
        return salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.sales_count
     *
     * @param salesCount the value for shop.sales_count
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setSalesCount(Integer salesCount) {
        this.salesCount = salesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.min_cost
     *
     * @return the value of shop.min_cost
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Float getMinCost() {
        return minCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.min_cost
     *
     * @param minCost the value for shop.min_cost
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setMinCost(Float minCost) {
        this.minCost = minCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.deliver_cost
     *
     * @return the value of shop.deliver_cost
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Float getDeliverCost() {
        return deliverCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.deliver_cost
     *
     * @param deliverCost the value for shop.deliver_cost
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setDeliverCost(Float deliverCost) {
        this.deliverCost = deliverCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.tags
     *
     * @return the value of shop.tags
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.tags
     *
     * @param tags the value for shop.tags
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.profile_pic
     *
     * @return the value of shop.profile_pic
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getProfilePic() {
        return profilePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.profile_pic
     *
     * @param profilePic the value for shop.profile_pic
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic == null ? null : profilePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.latitude
     *
     * @return the value of shop.latitude
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.latitude
     *
     * @param latitude the value for shop.latitude
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.longitude
     *
     * @return the value of shop.longitude
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.longitude
     *
     * @param longitude the value for shop.longitude
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }
}