package fun.jwei.hungerserver.model;

public class ShopCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.user_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.goods_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.sum
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer sum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.id
     *
     * @return the value of shop_car.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.id
     *
     * @param id the value for shop_car.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.user_id
     *
     * @return the value of shop_car.user_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.user_id
     *
     * @param userId the value for shop_car.user_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.goods_id
     *
     * @return the value of shop_car.goods_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.goods_id
     *
     * @param goodsId the value for shop_car.goods_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.sum
     *
     * @return the value of shop_car.sum
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.sum
     *
     * @param sum the value for shop_car.sum
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }
}