package fun.jwei.hungerserver.model;

import java.util.ArrayList;
import java.util.List;

public class ShopExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public ShopExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStarIsNull() {
            addCriterion("star is null");
            return (Criteria) this;
        }

        public Criteria andStarIsNotNull() {
            addCriterion("star is not null");
            return (Criteria) this;
        }

        public Criteria andStarEqualTo(Float value) {
            addCriterion("star =", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotEqualTo(Float value) {
            addCriterion("star <>", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThan(Float value) {
            addCriterion("star >", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThanOrEqualTo(Float value) {
            addCriterion("star >=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThan(Float value) {
            addCriterion("star <", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThanOrEqualTo(Float value) {
            addCriterion("star <=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarIn(List<Float> values) {
            addCriterion("star in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotIn(List<Float> values) {
            addCriterion("star not in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarBetween(Float value1, Float value2) {
            addCriterion("star between", value1, value2, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotBetween(Float value1, Float value2) {
            addCriterion("star not between", value1, value2, "star");
            return (Criteria) this;
        }

        public Criteria andSalesCountIsNull() {
            addCriterion("sales_count is null");
            return (Criteria) this;
        }

        public Criteria andSalesCountIsNotNull() {
            addCriterion("sales_count is not null");
            return (Criteria) this;
        }

        public Criteria andSalesCountEqualTo(Integer value) {
            addCriterion("sales_count =", value, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountNotEqualTo(Integer value) {
            addCriterion("sales_count <>", value, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountGreaterThan(Integer value) {
            addCriterion("sales_count >", value, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("sales_count >=", value, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountLessThan(Integer value) {
            addCriterion("sales_count <", value, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountLessThanOrEqualTo(Integer value) {
            addCriterion("sales_count <=", value, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountIn(List<Integer> values) {
            addCriterion("sales_count in", values, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountNotIn(List<Integer> values) {
            addCriterion("sales_count not in", values, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountBetween(Integer value1, Integer value2) {
            addCriterion("sales_count between", value1, value2, "salesCount");
            return (Criteria) this;
        }

        public Criteria andSalesCountNotBetween(Integer value1, Integer value2) {
            addCriterion("sales_count not between", value1, value2, "salesCount");
            return (Criteria) this;
        }

        public Criteria andMinCostIsNull() {
            addCriterion("min_cost is null");
            return (Criteria) this;
        }

        public Criteria andMinCostIsNotNull() {
            addCriterion("min_cost is not null");
            return (Criteria) this;
        }

        public Criteria andMinCostEqualTo(Float value) {
            addCriterion("min_cost =", value, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostNotEqualTo(Float value) {
            addCriterion("min_cost <>", value, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostGreaterThan(Float value) {
            addCriterion("min_cost >", value, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostGreaterThanOrEqualTo(Float value) {
            addCriterion("min_cost >=", value, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostLessThan(Float value) {
            addCriterion("min_cost <", value, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostLessThanOrEqualTo(Float value) {
            addCriterion("min_cost <=", value, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostIn(List<Float> values) {
            addCriterion("min_cost in", values, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostNotIn(List<Float> values) {
            addCriterion("min_cost not in", values, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostBetween(Float value1, Float value2) {
            addCriterion("min_cost between", value1, value2, "minCost");
            return (Criteria) this;
        }

        public Criteria andMinCostNotBetween(Float value1, Float value2) {
            addCriterion("min_cost not between", value1, value2, "minCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostIsNull() {
            addCriterion("deliver_cost is null");
            return (Criteria) this;
        }

        public Criteria andDeliverCostIsNotNull() {
            addCriterion("deliver_cost is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverCostEqualTo(Float value) {
            addCriterion("deliver_cost =", value, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostNotEqualTo(Float value) {
            addCriterion("deliver_cost <>", value, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostGreaterThan(Float value) {
            addCriterion("deliver_cost >", value, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostGreaterThanOrEqualTo(Float value) {
            addCriterion("deliver_cost >=", value, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostLessThan(Float value) {
            addCriterion("deliver_cost <", value, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostLessThanOrEqualTo(Float value) {
            addCriterion("deliver_cost <=", value, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostIn(List<Float> values) {
            addCriterion("deliver_cost in", values, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostNotIn(List<Float> values) {
            addCriterion("deliver_cost not in", values, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostBetween(Float value1, Float value2) {
            addCriterion("deliver_cost between", value1, value2, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andDeliverCostNotBetween(Float value1, Float value2) {
            addCriterion("deliver_cost not between", value1, value2, "deliverCost");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("tags is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("tags is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("tags =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("tags <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("tags >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("tags >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("tags <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("tags <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("tags like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("tags not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("tags in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("tags not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("tags between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("tags not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andProfilePicIsNull() {
            addCriterion("profile_pic is null");
            return (Criteria) this;
        }

        public Criteria andProfilePicIsNotNull() {
            addCriterion("profile_pic is not null");
            return (Criteria) this;
        }

        public Criteria andProfilePicEqualTo(String value) {
            addCriterion("profile_pic =", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicNotEqualTo(String value) {
            addCriterion("profile_pic <>", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicGreaterThan(String value) {
            addCriterion("profile_pic >", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicGreaterThanOrEqualTo(String value) {
            addCriterion("profile_pic >=", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicLessThan(String value) {
            addCriterion("profile_pic <", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicLessThanOrEqualTo(String value) {
            addCriterion("profile_pic <=", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicLike(String value) {
            addCriterion("profile_pic like", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicNotLike(String value) {
            addCriterion("profile_pic not like", value, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicIn(List<String> values) {
            addCriterion("profile_pic in", values, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicNotIn(List<String> values) {
            addCriterion("profile_pic not in", values, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicBetween(String value1, String value2) {
            addCriterion("profile_pic between", value1, value2, "profilePic");
            return (Criteria) this;
        }

        public Criteria andProfilePicNotBetween(String value1, String value2) {
            addCriterion("profile_pic not between", value1, value2, "profilePic");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbg.generated do_not_delete_during_merge Mon May 18 00:33:44 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}