package fun.jwei.hungerserver.model;

public class SwiperImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper_img.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper_img.title
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper_img.src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String src;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper_img.seq
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swiper_img.link
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String link;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper_img.id
     *
     * @return the value of swiper_img.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper_img.id
     *
     * @param id the value for swiper_img.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper_img.title
     *
     * @return the value of swiper_img.title
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper_img.title
     *
     * @param title the value for swiper_img.title
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper_img.src
     *
     * @return the value of swiper_img.src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper_img.src
     *
     * @param src the value for swiper_img.src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper_img.seq
     *
     * @return the value of swiper_img.seq
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper_img.seq
     *
     * @param seq the value for swiper_img.seq
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swiper_img.link
     *
     * @return the value of swiper_img.link
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swiper_img.link
     *
     * @param link the value for swiper_img.link
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }
}