package fun.jwei.hungerserver.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passwd
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.profile_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private String profileSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.curr_addr_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    private Long currAddrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passwd
     *
     * @return the value of user.passwd
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passwd
     *
     * @param passwd the value for user.passwd
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.profile_src
     *
     * @return the value of user.profile_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public String getProfileSrc() {
        return profileSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.profile_src
     *
     * @param profileSrc the value for user.profile_src
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setProfileSrc(String profileSrc) {
        this.profileSrc = profileSrc == null ? null : profileSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.curr_addr_id
     *
     * @return the value of user.curr_addr_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public Long getCurrAddrId() {
        return currAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.curr_addr_id
     *
     * @param currAddrId the value for user.curr_addr_id
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    public void setCurrAddrId(Long currAddrId) {
        this.currAddrId = currAddrId;
    }
}