package fun.jwei.hungerserver.mapper;

import fun.jwei.hungerserver.model.SwiperImg;
import fun.jwei.hungerserver.model.SwiperImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SwiperImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    long countByExample(SwiperImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int deleteByExample(SwiperImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int insert(SwiperImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int insertSelective(SwiperImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    List<SwiperImg> selectByExample(SwiperImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    SwiperImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") SwiperImg record, @Param("example") SwiperImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int updateByExample(@Param("record") SwiperImg record, @Param("example") SwiperImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int updateByPrimaryKeySelective(SwiperImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swiper_img
     *
     * @mbg.generated Mon May 18 00:33:44 CST 2020
     */
    int updateByPrimaryKey(SwiperImg record);
}